### ISSUE TITLE
USB device drivers and FTUSB interface 1

### ISSUE THREAD

**Issue by drizzd** [FPGAwars/libftdi-cross-builder#30]
I am on Windows 10 with USB 3.0. In the Wiki https://github.com/FPGAwars/libftdi-cross-builder/wiki#driver-installation we recommend installing the generic USB driver to both interfaces:

> NOTE: Windows 10 + USB 3.0 requires also to install libusb-win32 or libusbK to Lattice FTUSB Interface Cable (Interface 1)

However, find_all.exe and iceprog.exe work if I install the generic driver to interface 0 only, and it _breaks_ if I install it to both interfaces. I am do not know the background of this note, but could we update the note to say something like "If find_all does not work after installing to interface 0, try to install to interface 1 as well. However please note that installing to interface 1 breaks libftdi/libusb on some systems."

I reported my observations to the libusb folks here https://github.com/libusb/libusb/issues/370#issuecomment-365919954. There seems to be a general confusion regarding composite devices. Have we tried using usbdk https://www.slideshare.net/YanVugenfirer/usb-dk-ataglance1 instead, to see if it is less error prone?

**Comment by Obijuan** [comment]
Thanks! Note updated!

We have not try usbDK.  Good to know about it! :-)  Thanks!

I'll close the issue
